version: '3'
services:

  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    volumes:
      - ./web:/usr/src/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: 'mongo:latest'
    restart: always

  spa:
    build:
      dockerfile: Dockerfile
      context: ./spa
    volumes:
      - /app/node_modules
      - ./spa:/app

  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - '80:80'
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf