FROM python:3.8-alpine
WORKDIR /usr/src/app

COPY ./requirements.txt ./
RUN pip install  --no-cache-dir -r requirements.txt

RUN apk add --update --no-cache py3-numpy
ENV PYTHONPATH=/usr/lib/python3.8/site-packages

COPY . .
CMD ["python", "app.py"]